exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']  # needed for !! tags in mkdocs.yml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

# Ruff replaces flake8, autoflake and isort
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.275'
  hooks:
    - id: ruff

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3

# black style for code in the docs:
- repo: https://github.com/asottile/blacken-docs
  rev: 1.14.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]
    exclude: docs/examples  # Exclude since blacken-docs cannot handle the >>> needed for doctests

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.4.0'  # Use the sha / tag you want to point at
  hooks:
    - id: mypy
      additional_dependencies: [types-tabulate, types-cachetools]
