[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

####################
# Project Metadata #
####################

[project]
name = "ultimate-notion"
description = "The ultimate Python library for Notion!"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["notion", "notion client"]
authors = [
    { name = "Florian Wilhelm", email = "Florian.Wilhelm@gmail.com" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    # ToDo: Remove direct reference when new version is released
    "notion-client @ git+https://github.com/FlorianWilhelm/notion-sdk-py@description_param",
    "tabulate",
    "numpy",
    "pandas",
    "emoji",
    "pandas",
    "pydantic>=2",
#    "google-api-python-client",
#    "google-auth-httplib2",
#    "google-auth-oauthlib",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://ultimate-notion.com/"
Sponsor = "https://github.com/sponsors/FlorianWilhelm"
Tracker = "https://github.com/ultimate-notion/ultimate-notion/issues"
Source = "https://github.com/ultimate-notion/ultimate-notion"

######################
# Build & Versioning #
######################

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
source = "vcs"
raw-options = { version_scheme = "no-guess-dev" }

[tool.hatch.build.hooks.vcs]
version-file = "src/ultimate_notion/_version.py"

[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
]

##################
# External Tools #
##################

[tool.mypy]
files = ["src/ultimate_notion", "tests"]
exclude = ["src/ultimate_notion/obj_api/.*"]  # ToDo: Remove this later on
disallow_untyped_defs = false
follow_imports = "silent"  # ToDo: make "normal" after obj_api is consistent
ignore_missing_imports = true
pretty = true
show_column_numbers = true
warn_no_return = false
warn_unused_ignores = true

[tool.black]
include = '\.pyi?$'
line-length = 120
skip-string-normalization = true
target-version = ["py310"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --doctest-glob='*.md'"
testpaths = [
    "tests",
]
markers = [
    "webtest: tests that use the Notion web API"
]

[tool.coverage.run]
branch = true
source = ["src/ultimate_notion"]
# omit = [
#   "bad_file.py",
# ]
#

[tool.coverage.paths]
source = [
    "src/",
    "*/site-packages/",
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

[tool.ruff]
target-version = "py310"
line-length = 120
preview = true
#include = ["src/**/*.py", "src/**/*.pyi", "**/pyproject.toml"]
exclude = ["examples/*\\.py"] # ToDo: remove & fix later
select = [
  "A",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT", # Boolean trap
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "SIM",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
  "RUF100", # Automatically remove unused # noqa directives
]
ignore = [
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105", "S106", "S107",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
  "PLC1901", # empty string comparisons
  "PLW2901", # `for` loop variable overwritten
  "SIM114", # Combine `if` branches using logical `or` operator
  "E203", # Whitespace before :, needed for black compatability
]
unfixable = [
  # "F401",  # Don't touch unused imports
]

[tool.ruff.isort]
known-first-party = ["ultimate_notion"]

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.per-file-ignores]
# Allow print/pprint
"examples/*" = ["T201"]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]


#####################
# Environment Setup #
#####################

# Default environment
[tool.hatch.envs.default]
dependencies = [
    "hatch",
    "hatch-vcs", # to make `hatch version` available
    "coverage[toml]>=6.2",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-vcr",
    "pytest-env",
    "hypothesis",
    "jupyterlab",
    "pre-commit",
    "mypy",
    "ruff",
    "seaborn",
    "scipy",
    "pandas",
    "ipython",
    "mktestdocs",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=src/ultimate_notion --cov=tests {args}"
no-cov = "cov --no-cov {args}"
debug =  "cov --no-cov -s --pdb --pdbcls=IPython.core.debugger:Pdb {args}"
ci = "cov --vcr-record=none --cov-report lcov {args}"
record = "cov --vcr-record=all {args}" # re-record all vcr cassettes
doctest = "pytest docs/examples/"

# Docs environment
[tool.hatch.envs.docs]
dependencies = [
    "mkdocs~=1.4.0",
    "mkdocs-material~=8.5.6",
    # Plugins
    "mkdocs-include-markdown-plugin",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-minify-plugin~=0.5.0",
    "mkdocs-section-index",
    "mkdocs-git-revision-date-localized-plugin~=1.1.0",
    "mkdocstrings[python]",
    "mkdocs-redirects~=1.1.0",
    "mkdocs-glightbox~=0.3.0",
    # https://github.com/jimporter/mike/issues/82#issuecomment-1172913929
    "mike @ https://github.com/jimporter/mike/archive/392d57b8bb9d14bcedf2451a0dc302709f8055eb.zip",
    # Extensions
    "pymdown-extensions~=9.6.0",
    # Necessary for syntax highlighting in code blocks
    "pygments~=2.13.0",
    # Validation
    # https://github.com/linkchecker/linkchecker/pull/669#issuecomment-1267236287
    "linkchecker @ git+https://github.com/linkchecker/linkchecker.git@d9265bb71c2054bf57b8c5734a4825d62505c779",
    ]
[tool.hatch.envs.docs.env-vars]
SOURCE_DATE_EPOCH = "1580601600"
PYTHONUNBUFFERED = "1"
MKDOCS_CONFIG = "mkdocs.yml"
[tool.hatch.envs.docs.scripts]
build = "mkdocs build --config-file {env:MKDOCS_CONFIG} --clean --strict {args}"
serve = "mkdocs serve --config-file {env:MKDOCS_CONFIG} --dev-addr localhost:8000 {args}"
ci-build = "mike deploy --config-file {env:MKDOCS_CONFIG} --update-aliases {args}"
# --ignore-url=None since the SUMMARY.md file leaves a <toc>None</toc> in sitemap.xml
validate = "linkchecker --config .linkcheckerrc --ignore-url=/reference --ignore-url=None site"
# https://github.com/linkchecker/linkchecker/issues/678
build-check = [
    "build",
    "validate",
]

# Lint environment
[tool.hatch.envs.lint]
skip-install = true
dependencies = [
    "black>=23.1.0",
    "mypy>=1.0.0",
    "ruff>=0.0.259",
]
[tool.hatch.envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args}"
style = [
    "ruff {args:.}",
    "black --check --diff .",
]
fmt = [
    "black {args:.}",
    "ruff --fix {args:.}",
    "style",
]
all = [
    "style",
    "typing",
]

# Test matrix replacing the functionality of tox
[[tool.hatch.envs.test.matrix]]
python = ["310", "311"]
