name: "💡 Feature Request"
description: Suggest a feature for Ultimate Notion.
title: "💡 [REQUEST] - <title>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to write a feature request, it's much appreciated! Please make also sure to search our issues for similar feature requests first. If the requests exists already, react with a thumbs-up to indicate your interest. If a similar issue exists, either leave a comment there or link the issue here.
  - type: textarea
    id: problem
    attributes:
      label: Describe your use-case or problem
      description: What problem you're running into? What do use-case do you have in mind?
      placeholder: "When trying to do ____, Ultimate Notion doesn't allow me to do ____, which is a problem because ____."
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution / feature
      description: How would Ultimate Notion behave in an ideal world? What would make your life easier?
      placeholder: Ideally, I could do ____ directly, with helpful suggestions drawing from my recent search.
  - type: textarea
    id: context
    attributes:
      label: Additional context or examples
      description: Providing context and examples helps us to choose a solution that is the most useful for all uers of Ultimate Notion.
