name: Build & Publish Docs

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-deploy
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch all history for applying timestamps to every page
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Ensure latest pip
      run: python -m pip install --upgrade pip

    - name: Install Hatch
      run: pip install --upgrade --pre hatch

    - name: Install ourself
      run: pip install -e .

    - name: Configure Git for GitHub Actions bot
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Build documentation
      run: hatch run docs:build-check

    - name: Commit documentation
      run: hatch run docs:ci-build dev

    - name: Create archive
      run: git archive -o site.zip gh-pages

    - uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: site.zip

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
    - build

    steps:
    - name: Download Archive
      uses: actions/download-artifact@v3
      with:
        name: documentation

    - name: Unpack Archive
      run: python -m zipfile -e site.zip site

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload Pages
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: 'site/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

#    - uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: site
#        commit_message: ${{ github.event.head_commit.message }}
#        # Write .nojekyll at the root, see:
#        # https://help.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators
#        enable_jekyll: false
#        # Only deploy if there were changes
#        allow_empty_commit: false
